# Deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        resources:
          requests:
            cpu: "125m"
            memory: "250Mi"
          limits:
            cpu: "125m"
            memory: "250Mi"
        ports:
        - containerPort: 5672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deploy
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      hostname: sqlserver
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server
#        resources:
#          requests:
#            cpu: "500m"
#            memory: "750Mi"
#          limits:
#            cpu: "500m"
#            memory: "750Mi"
        env:
        - name: SA_PASSWORD
          value: "TCCpurchase01"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: redis
      containers:
      - name: redis-container
        image: redis:4-alpine
        resources:
          requests:
            cpu: "125m"
            memory: "250Mi"
          limits:
            cpu: "125m"
            memory: "250Mi"
        ports:
        - containerPort: 6379

---

# Services

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: messagebus
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672

---

apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  externalName: sqlserver
  selector:
    app: sqlserver
  ports:
  - name: database
    port: 1433
    targetPort: 1433

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - name: database
    port: 6379
    targetPort: 6379







---
apiVersion: v1
kind: Service
metadata:
  name: erp-purchasing-service
spec:
  selector:
    app: erp-purchasing-pod
  ports:
  - name: http
    port: 5000
    targetPort: 80
  - name: https
    port: 5001
    targetPort: 443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-purchasing-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-purchasing-pod
  template:
    metadata:
      labels:
        app: erp-purchasing-pod
    spec:
      containers:
      - name: erp-purchasing-container
        image: 310194/erp_purchasingapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: SQL_SERVER_HOST
            value: "sqlserver-service"
          - name: SQL_SERVER_PORT
            value: "1433"
          - name: SQL_SERVER_DATA_BASE
            value: Inventory
          - name: SQL_SERVER_USER_NAME
            value: sa
          - name: SQL_SERVER_PASSWORD
            value: TCCpurchase01
          - name: RABBITMQ_HOST_NAME
            value: rabbitmq-service
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: guest
          - name: RABBITMQ_PASSWORD
            value: guest
          - name: RABBITMQ_EXCHANGE
            value: erp_message_bus
          - name: RABBITMQ_QUEUE_NAME
            value: purchasing
        ports:
        - containerPort: 80
        - containerPort: 443