# Services

apiVersion: v1
kind: Service
metadata:
  name: erp-quotes-service
spec:
  externalName: erp-quotes
  selector:
    app: erp-quotes
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---

# Deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-quotes-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-quotes
  template:
    metadata:
      labels:
        app: erp-quotes
    spec:
      containers:
      - name: erp-quotes-container
        image: rafaelgalani/crm_quotes:22-06-no-nameko
        resources:
          requests:
            cpu: "150m"
            memory: "300Mi"
          limits:
            cpu: "300m"
            memory: "600Mi"
        env:
          - name: FIRED_EVENT_ROUTING_KEY
            value: "createdOrderEvent"
          - name: MESSAGE_BUS_NAME
            value: "erp_message_bus"
          - name: RABBIT_HOST
            value: rabbitmq-service
          - name: RABBIT_PORT
            value: "5672"
          - name: RABBIT_USER
            value: guest
          - name: RABBIT_PASSWORD
            value: guest
          - name: REDIS_HOST
            value: redis-service
          - name: REDIS_PORT
            value: "6379"
        ports:
        - containerPort: 8000

---

# HPAs

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: erp-quotes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-quotes-deploy
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 225m 
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 450Mi