# Services

apiVersion: v1
kind: Service
metadata:
  name: erp-inventory-service
spec:
  externalName: erp-inventory
  selector:
    app: erp-inventory
  ports:
  - name: http
    port: 5004
    targetPort: 80
  - name: https
    port: 5005
    targetPort: 443 
  type: LoadBalancer

---

# Deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-inventory
  template:
    metadata:
      labels:
        app: erp-inventory
    spec:
      containers:
      - name: erp-inventory-container
        image: 310194/erp_inventoryapi
        resources:
          requests:
            cpu: "125m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
          - name: SQL_SERVER_HOST
            value: sqlserver-service
          - name: SQL_SERVER_PORT
            value: "1433"
          - name: SQL_SERVER_DATA_BASE
            value: Inventory
          - name: SQL_SERVER_USER_NAME
            value: sa
          - name: SQL_SERVER_PASSWORD
            value: TCCpurchase01
          - name: RABBITMQ_HOST_NAME
            value: rabbitmq-service
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: guest
          - name: RABBITMQ_PASSWORD
            value: guest
          - name: RABBITMQ_EXCHANGE
            value: erp_message_bus
          - name: RABBITMQ_QUEUE_NAME
            value: inventory
        ports:
        - containerPort: 80
        - containerPort: 443

---

# HPAs

# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: erp-inventory-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: erp-inventory-deploy
#   minReplicas: 1
#   maxReplicas: 8
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Value
#         averageValue: 100m 
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: AverageValue
#         averageValue: 200Mi