# Deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-purchase-deploy
  labels:
    app: erp-purchase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-purchase
  template:
    metadata:
      labels:
        app: erp-purchase
    spec:
      containers:
      - name: erp-purchase
        image: laionfb/erp_purchase:v9
        resources:
          requests:
            cpu: "150m"
            memory: "300Mi"
          limits:
            cpu: "300m"
            memory: "600Mi"
        env:
        - name: PORT
          value: "80"
        - name: API_GATEWAY_PATH
          value: "/api/purchase"
        - name: SQL_SERVER_HOST
          value: tcc-microservices.database.windows.net
        - name: SQL_SERVER_PORT
          value: "1433"
        - name: SQL_SERVER_USER
          value: tcc
        - name: SQL_SERVER_PASSWORD
          value: Micro@2020
        - name: SQL_SERVER_DATA_BASE
          value: Purchase
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_EXCHANGE
          value: erp_message_bus
        - name: RABBITMQ_QUEUE
          value: purchasing
        - name: DB_SYNC_DATABASE
          value: "N"
        - name: DB_SYNC_TABLES
          value: "N"
        - name: DB_SYNC_DATA
          value: "N"
        ports:
        - containerPort: 80

---

# Services

apiVersion: v1
kind: Service
metadata:
  name: erp-purchase-service
spec:
  externalName: erp-purchase
  selector:
    app: erp-purchase
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

---

# HPAs

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: erp-purchase-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-purchase-deploy
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 225m 
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 450Mi